services:
  mysql:
    image: mysql:8.0
    container_name: orders-system-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders_db
      MYSQL_USER: orders_user
      MYSQL_PASSWORD: orders_pass
    ports:
      - "3306:3306"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
      - mysql_data:/var/lib/mysql
    networks:
      - orders-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  customers-api:
    build:
      context: ./customers-api
      dockerfile: Dockerfile
    container_name: orders-system-customers-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: orders_db 
      SERVICE_TOKEN: 151cbcf56116e0236bd247ab1f8702cab277b6569116a2bbd4561a7798ab3fec
    depends_on:
      - mysql
    networks:
      - orders-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./customers-api/src:/app/src:ro

  orders-api:
    build:
      context: ./orders-api
      dockerfile: Dockerfile
    container_name: orders-system-orders-api
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: development
      PORT: 3002
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: orders_db
      SERVICE_TOKEN: 151cbcf56116e0236bd247ab1f8702cab277b6569116a2bbd4561a7798ab3fec
      CUSTOMERS_API_BASE: http://customers-api:3001
    depends_on:
      - mysql
      - customers-api
    networks:
      - orders-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: sh -c "npm run migrate && npm run seed && npm start"
    volumes:
      - ./orders-api/src:/app/src:ro
      - ./db:/app/db:ro


  adminer:
    image: adminer:latest
    container_name: orders-system-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    networks:
      - orders-network


networks:
  orders-network:
    driver: bridge
    name: orders-system-network


volumes:
  mysql_data:
    driver: local
    name: orders-system-mysql-data