service: orders-orchestrator

configValidationMode: off

provider:
  name: aws
  runtime: nodejs22.x
  architecture: arm64
  region: us-east-2
  stage: prod
  environment:
    CUSTOMERS_API_BASE: ${env:CUSTOMERS_API_BASE}
    ORDERS_API_BASE: ${env:ORDERS_API_BASE}
    SERVICE_TOKEN: ${env:SERVICE_TOKEN}
  httpApi:
    cors: true

functions:
  createAndConfirmOrder:
    handler: src/handler.createAndConfirmOrder
    events:
      - httpApi:
          path: /orchestrator/create-and-confirm-order
          method: post
  health:
    handler: src/handler.health
    events:
      - httpApi:
          path: /health
          method: get

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: ${env:PORT, 3000}
    noPrependStageInUrl: true